Add support for ld.gold function tracking
xalt checks for a function name from a backtick to a quote
in the "undefined reference to `func_name'" message returned
by the linker. Because ld.gold puts the function name between 2 quotes,
the resulting function name is empty.